import Head from 'next/head'
import Brands from './components/Brands'
import HeroSection from './components/HeroSection'
import SucessStories from './components/SuccessStories'
import WhatWeDo from './components/WhatWeDo'

export default function Home() {
  return (
    <div className="Main">
      <Head>
        <title>CoreProc, Inc | The Best Web and Mobile App Development Company in the Philippines</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#465361" />
        <meta name="msapplication-TileColor" content="#465361" />
        <meta name="theme-color" content="#465361" />
      </Head>

      <div className="w-full h-auto">
        <div className="overflow-x-hidden">
          <HeroSection />
          <WhatWeDo />
          <SucessStories />
          <Brands />
        </div>
      </div>
    </div>
  )
}
